
author: 管宜尧
github: https://github.com/mylxsw
weibo: http://weibo.com/code404
icp: 鲁ICP备14009006号
site_name: AiCode
site_title: 爱生活，爱代码 - AICODE

base_url:
production_url: http://blog.aicode.cc


encoding: utf-8
timezone: Asia/Shanghai
highlighter: pygments
paginate: 10


defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: default
      author: 管宜尧
      disqus: true
      sidebar: true
      navbar: 技术文章
